### ISSUE TITLE
Regression in combine

### ISSUE THREAD

**Issue by solnic** [solnic/transproc#92]
So specs are failing in one of my apps with this backtrace:

```
      NoMethodError:
        undefined method `group_by' for nil:NilClass
      # /Users/solnic/.gem/ruby/2.4.0/gems/transproc-1.0.1/lib/transproc/array/combine.rb:46:in `group_candidates_by_keys'
      # /Users/solnic/.gem/ruby/2.4.0/gems/transproc-1.0.1/lib/transproc/array/combine.rb:39:in `group_candidates'
      # /Users/solnic/.gem/ruby/2.4.0/gems/transproc-1.0.1/lib/transproc/array/combine.rb:32:in `block in group_nodes'
      # /Users/solnic/.gem/ruby/2.4.0/gems/transproc-1.0.1/lib/transproc/array/combine.rb:30:in `each'
      # /Users/solnic/.gem/ruby/2.4.0/gems/transproc-1.0.1/lib/transproc/array/combine.rb:30:in `each_with_index'
      # /Users/solnic/.gem/ruby/2.4.0/gems/transproc-1.0.1/lib/transproc/array/combine.rb:30:in `each'
      # /Users/solnic/.gem/ruby/2.4.0/gems/transproc-1.0.1/lib/transproc/array/combine.rb:30:in `map'
      # /Users/solnic/.gem/ruby/2.4.0/gems/transproc-1.0.1/lib/transproc/array/combine.rb:30:in `group_nodes'
      # /Users/solnic/.gem/ruby/2.4.0/gems/transproc-1.0.1/lib/transproc/array/combine.rb:8:in `combine'
      # /Users/solnic/.gem/ruby/2.4.0/gems/transproc-1.0.1/lib/transproc/array.rb:123:in `combine'
      # /Users/solnic/.gem/ruby/2.4.0/gems/transproc-1.0.1/lib/transproc/function.rb:47:in `call'
      # /Users/solnic/.gem/ruby/2.4.0/gems/transproc-1.0.1/lib/transproc/function.rb:47:in `call'
      # /Users/solnic/.gem/ruby/2.4.0/gems/transproc-1.0.1/lib/transproc/composite.rb:30:in `call'
      # /Users/solnic/.gem/ruby/2.4.0/gems/rom-mapper-0.5.0/lib/rom/mapper.rb:95:in `block in call'
      # /Users/solnic/.gem/ruby/2.4.0/gems/rom-mapper-0.5.0/lib/rom/mapper.rb:95:in `each'
      # /Users/solnic/.gem/ruby/2.4.0/gems/rom-mapper-0.5.0/lib/rom/mapper.rb:95:in `reduce'
      # /Users/solnic/.gem/ruby/2.4.0/gems/rom-mapper-0.5.0/lib/rom/mapper.rb:95:in `call'
      # /Users/solnic/.gem/ruby/2.4.0/gems/rom-3.0.1/lib/rom/relation/composite.rb:22:in `call'
      # /Users/solnic/.gem/ruby/2.4.0/gems/rom-repository-1.1.0/lib/rom/repository/relation_proxy.rb:51:in `call'
      # /Users/solnic/.gem/ruby/2.4.0/gems/rom-3.0.1/lib/rom/relation/materializable.rb:20:in `to_a'
```

Looks like previously when candidates was nil it'd just skip them, now it tries to group w/o a nil check

**Comment by Kukunin** [comment]
can you dump what's going to #combine and I'll fix it soon?
